### ISSUE TITLE
Error on collectstatic using django 1.11 python 3.6

### ISSUE THREAD

**Issue by debaze** [jazzband/collectfast#100]
Hi ,

I'm trying to move my Django project (which uses collectstatic) from python 2.7 to python 3.6.

When running collectstatic from the command line I get an error (see further). As everything else works fine, I'm a bit lost on what went wrong here.

I did not change my settings.py and all worked fine under python 2.7

Thanks for pointing me in the right direction!

Regards,
Joris

The error:

```
(platform)baze@baze-mintbox:~/dev/www/projects/ieper/platform > python manage.py collectstatic

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/collectfast/management/commands/collectstatic.py", line 70, in handle
    super(Command, self).handle(**options)
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/collectfast/management/commands/collectstatic.py", line 61, in collect
    ret = super(Command, self).collect()
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
    handler(path, prefixed_path, storage)
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/collectfast/management/commands/collectstatic.py", line 109, in copy_file
    self.do_copy_file(args)
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/collectfast/management/commands/collectstatic.py", line 86, in do_copy_file
    self.storage, path, prefixed_path, source_storage):
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/collectfast/etag.py", line 93, in should_copy_file
    remote_storage, source_storage, path, prefixed_path):
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/collectfast/etag.py", line 83, in has_matching_etag
    storage_etag = get_etag(remote_storage, path, prefixed_path)
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/collectfast/etag.py", line 58, in get_etag
    etag = get_remote_etag(storage, prefixed_path)
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/collectfast/etag.py", line 38, in get_remote_etag
    normalized_path = storage._normalize_name(
  File "/home/baze/dev/virtualenvs/platform/lib/python3.6/site-packages/django/utils/functional.py", line 239, in inner
    return func(self._wrapped, *args)
AttributeError: 'StaticFilesStorage' object has no attribute '_normalize_name'\
```

For reference, my pip freeze output:

boto==2.46.1
boto3==1.4.4
botocore==1.5.40
certifi==2017.4.17
chardet==3.0.4
Collectfast==0.5.2
defusedxml==0.5.0
dj-database-url==0.4.2
Django==1.11
django-allauth==0.32.0
django-postgrespool==0.3.1
django-storages==1.5.2
docutils==0.13.1
futures==3.1.1
gunicorn==19.7.1
idna==2.5
jmespath==0.9.2
newrelic==2.86.3.70
oauthlib==2.0.2
psycopg2==2.7.1
python-dateutil==2.6.0
python3-openid==3.1.0
pytz==2017.2
requests==2.17.3
requests-oauthlib==0.8.0
s3transfer==0.1.10
six==1.10.0
SQLAlchemy==1.1.10
urllib3==1.21.1

**Comment by antonagestam** [comment]
What's your `STATICFILES_STORAGE` setting?

**Comment by debaze** [comment]
Your comment pointed me in the right direction, thanks!

STATICFILES_STORAGE was not (properly) defined due to sloppy refactoring. This caused the error.

setting it back to
STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

resolved the issue

Sorry to bother you with this trivial mistake, and thanks again!

Joris

**Comment by antonagestam** [comment]
No worries, I'm happy to help. Maybe we should add a friendlier error message or warning if it's not set to boto?

**Comment by debaze** [comment]
That would be handy. The error message is a bit cryptic for those, like me, who are not very experienced with django/python. That made me wrongly think it had to do something with upgrading to python 3.6.

I might submit a pull request if I find time this summer.

Regards,
Joris

**Comment by antonagestam** [comment]
Very cool, let me know if I can assist you to make that happen. It could probably be something along the lines below added in https://github.com/jazzband/collectfast/blob/master/collectfast/management/commands/collectstatic.py#L36

```python
if not hasattr(self.storage, '_normalize_name'):
    raise AttributeError(
        "The `STATICFILES_STORAGE` class needs to implement a `_normalize_name` method. Note that `storages.backends.s3boto.S3BotoStorage` from django-storages is the only class that Collectfast officially supports.")
```

**Comment by debaze** [comment]
Perfect. After my current deadline (1st of july), I will dive into it. Collectstatic is and has been very helpful to me, so it will be a pleasure to do something back, even if it's small. Regards and talk to you later!
